import { Provider } from './provider'
import './reset.scss'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Guider',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
